### ISSUE TITLE
KCL needs lexical scope for variables

### ISSUE THREAD

**Issue by adamchalmers** [KittyCAD/modeling-app#2440] opened 2024-05-21 23:09 UTC
Currently, this program won't run:

```kcl
fn f = (x) => {
  return 2 * x
}

let x = 4
f(x)
```

It gives the error "Cannot redefine x". This should be totally legal, though. `x` the parameter and `x` the top-level binding should be in different scopes.

**Comment by jessfraz** [comment] 2024-05-21 23:39
this is a dupe of https://github.com/KittyCAD/modeling-app/issues/1285

**Closed by jessfraz** 2024-05-21 23:39 UTC
Labels: bug, kcl
