### ISSUE TITLE
Better prompt the user about the "More than 2 connections" error

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1788] opened 2024-03-20 23:11 UTC
We show the user that there is a WebSocket error in the NetworkHealthIndicator, but we should surface more directly to the user that they may need to close open tabs or apps.

**Comment by jessfraz** [comment] 2024-05-21 06:24
closing as dupe of https://github.com/KittyCAD/modeling-app/issues/1198

**Closed by jessfraz** 2024-05-21 06:24 UTC
Labels: ux papercut
