### ISSUE TITLE
KCL: Ability to reuse variable names in different scopes

### ISSUE THREAD

**Issue by greg-kcio** [KittyCAD/modeling-app#1527] opened 2024-02-27 00:37 UTC
Variables declared within a specific scope should be considered independent of variables with the same name in different scopes. Therefore a variable declared inside a function should not conflict with a variable of the same name defined outside the function.

Currently, this is not valid KCL:

```
fn rect = (x, y, w, h) => {
  startSketchOn('XY')
    |> startProfileAt([x, y], %)
    |> xLine(w, %)
    |> yLine(h, %)
    |> xLine(-w, %)
    |> close(%)
}

fn two_rects = (x, y, w, h, p) => {
  rect(x, y, w, h)
  rect(x + w + p, y, w, h)
}
```

So I have to do this:

```
fn rect = (x1, y1, w1, h1) => {
  startSketchOn('XY')
    |> startProfileAt([x1, y1], %)
    |> xLine(w1, %)
    |> yLine(h1, %)
    |> xLine(-w1, %)
    |> close(%)
}

fn two_rects = (x, y, w, h, p) => {
  rect(x, y, w, h)
  rect(x + w + p, y, w, h)
}
```

**Comment by jessfraz** [comment] 2024-02-29 03:22
dupe of https://github.com/KittyCAD/modeling-app/issues/1285

**Closed** 2024-02-29 03:22 UTC
Labels: kcl
