### ISSUE TITLE
When sketching on the XY axis, the Zoo API responds with "Cannot set the camera position with these values"

### ISSUE THREAD

**Issue by paultag** [KittyCAD/modeling-app#3339] opened 2024-08-09 19:12 UTC
Steps to reproduce:

 1. Start Sketch
 2. Click on the red plane
 3. Open debug console output

```
Uncaught (in promise) engine error: [{"error_code":"bad_request","message":"Cannot set the camera position with these values"}]
```

This triggers because the camera "Up" vector is exactly in line with the commanded view vector, which causes bad things graphically. A different "Up" vector ought to be picked when viewing this axis. This is also the *camera*, not *global* up vector -- doing this won't change the spatial orientation of any of the objects under modeling.

**Comment by paultag** [comment] 2024-08-09 19:13
(as followup and only for awareness: @adamchalmers @franknoirot @mlfarrell)

**Comment by adamchalmers** [comment] 2024-08-09 19:14
What vector should we pick? I don't really understand why we can't look at whatever damn plane we please. But whatever.

**Comment by paultag** [comment] 2024-08-09 19:16
@adamchalmers We can look in any direction, we just need the camera "up" to be something other than our view direction -- this isn't to say we can't look globally up -- just the *camera*'s up vector can't be the same as the *camera*'s view vector, as I understand it. Not that the Camera can't look directly up

**Comment by paultag** [comment] 2024-08-09 19:17
maybe helpful diagram from the internet 
![image](https://github.com/user-attachments/assets/490adff9-cf68-467a-85f3-83b5075c562d)

You can see the camera's up/down/left/right/front/back arrows, and the view (out the large part) vector. Those can be changed without changing the scene's / global up/down/left/right/front/back

**Comment by paultag** [comment] 2024-08-09 19:18
(You could imagine a world where we control the camera up as we change our view, and always look "forward", I have no idea if that's the fix here or not, just swapping the vectors? This one is outside my expertise - I'm just repeating what I understood)

**Comment by mlfarrell** [comment] 2024-08-09 19:27
> What vector should we pick? I don't really understand why we can't look at whatever damn plane we please. But whatever.

```c++    bool Camera::lookAt(const vec3 &vantage, const vec3 &center, vec3 up)
    {
        //detect problem first (we only need to do this in this scenario to avoid gymbal-locky/singularity type situations)
        //dont allow the eye vector to be exactly along the up vector
        if(abs(abs(glm::dot(glm::normalize(vantage - center), glm::normalize(up))) - 1.0f) < Constants::COARSE_EPSILON)
        {
             //pick a new "up" reference.  
              //{ 0, 1, 0 } is probably fine Y-up instead of Z-up 
        }
```

**Comment by mlfarrell** [comment] 2024-08-09 19:31
to explain slightly further.  The problem is with the way "look at" is essentially defining the camera orientation.  if we had an API to just set the camera as a position + a quaternion, this type of ambiguity would go away.  But it'd also be much harder on API users.  Camera Ppl are very used to "look at", hence why we provide it.

**Comment by nadr0** [comment] 2024-09-06 17:25
I was looking into this [issue](https://github.com/KittyCAD/modeling-app/issues/3307) which is a duplicate of this ticket. 
> I also can't iterate enough, we do not want to use the camera local-up vector for this. I tried that once since its counter-intuitively wrong and it broke the camera pretty bad. It should be a consistent reference of "up", which works for all scenarios except the singularity shown above

If we cannot pass a different up vector and we always pass in `<0,0,1>` the entire use workflow for editing XY axis gets bricked. 

I tested this out locally https://github.com/KittyCAD/modeling-app/pull/3806/files and it "works" but I guess it works for the wrong reason? 

Here are the up vectors it sends in the main `branch`
XY it sends `<0,0,1>` which is the singularity issue
XZ it sends `<0,0,1>` which works
YZ it sends `<0,0,1>` which works

When I change it to use the upVector of the camera it sends 
XY it sends `<0,1,0>` which looks like it visually works but you are saying is wrong? 
XZ it sends `<0,0,1>` which works
YZ it sends `<0,0,1>` which works

**Comment by nadr0** [comment] 2024-09-10 16:47
Solved in https://github.com/KittyCAD/modeling-app/issues/3307, closing this since it is fixed and this is a dupe.

**Closed by nadr0** 2024-09-10 16:47 UTC
Labels: bug
