### ISSUE TITLE
Closing the KCL Code pane and re-openining ruins the syntax highlighting in dark mode

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#3080] opened 2024-07-19 11:01 UTC
## Steps to reproduce
1. start the app with the code pane open and some code inside, with the dark theme
2. close it
3. open it

The syntax highlighting theme is wiped for a much uglier one

https://github.com/user-attachments/assets/cc9a2b38-a68f-4e9b-bb2b-88042d522490

**Comment by jessfraz** [comment] 2024-07-19 14:05
Dupe of https://github.com/KittyCAD/modeling-app/issues/3077 where we were already debugging

**Closed by jessfraz** 2024-07-19 14:05 UTC
Labels: bug, codemirror
