### ISSUE TITLE
Stream shows the inside of sketch after extrude

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2998] opened 2024-07-10 15:21 UTC
🐛

Steps to reproduce:
1. Login
2. Clear default sketch
3. Start a new sketch
4. Select a plane
5. Draw a square or use rectangle tool to draw one
6. Exit sketch
7. Click the sketch
8. Click "Extrude" button
9. Enter a distance value of at least ~15
Expected: To view the extruded sketch at a reasonable scale
Actual: The view is the inside of the extruded sketch

Timestamp: 0:11
Video: 
https://www.loom.com/share/9db8ba018edf46e7bd5452e0badae717 (https://www.loom.com/share/9db8ba018edf46e7bd5452e0badae717)

Bug report:
https://app.qawolf.com/zoo/bug-reports/fd93b4d3-6b42-4ba7-a551-c38a6a55fd37

Affected workflows:

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by franknoirot** [comment] 2024-08-05 10:30
I think to reproduce you have to select the "XZ" plane. I thought we had zoom-to-fit fire on extrude, and that would pop us out of the resulting extrusion, I'll have to take a look if that's not firing anymore.

**Comment by Irev-Dev** [comment] 2024-08-05 10:30
This was actually solved when Lee added "zoom_to_fit" on extrude, but zoom to fit was being weird and making the whole scene look empty, because the user ending up inside the object is better than loosing the scene entirely I re-introduced this bug as a compromise with https://github.com/KittyCAD/modeling-app/pull/3276

And have raised this https://github.com/KittyCAD/engine/issues/2417 in the engine.

**Comment by lf94** [comment] 2024-08-06 01:20
So we're waiting on engine to fix?

**Comment by franknoirot** [comment] 2024-08-06 12:21
Just double checking, that part of the problem with our Reset Camera button and function isn't that we update the camera's position to a fixed number before calling `zoom_to_fit`? We send this engine command before the zoom_to_fit in [CameraControls.resetCameraPosition](https://github.com/KittyCAD/modeling-app/blob/main/src/clientSideScene/CameraControls.ts#L838-L851):
```ts
await this.engineCommandManager.sendSceneCommand({
      type: 'modeling_cmd_req',
      cmd_id: uuidv4(),
      cmd: {
        type: 'default_camera_look_at',
        center: this.target,
        vantage: {
          x: this.target.x,
          y: this.target.y - 128,
          z: this.target.z + 64,
        },
        up: { x: 0, y: 0, z: 1 },
      },
    })
```

are the `128` and `64` unit-less? And is the engine okay with us calling a camera move command immediately followed by a command that moves and zooms, or could that cause issues? Just seeing if our use of the API could contribute at all.

**Comment by Irev-Dev** [comment] 2024-08-07 00:10
Reset camera is fine, zoom to fit has issues outside of the reset camera gizmo button. for example https://github.com/KittyCAD/modeling-app/issues/3217

zoom to fit does not change the camera's orientation only it position, so setting the camera to 
![image](https://github.com/user-attachments/assets/eb5de65d-2ff7-4d8a-899f-87b07b0bd18a)

First just has the effect of putting the camera back to where it normally start with, so it's like resetting the scene.

**Comment by Irev-Dev** [comment] 2024-08-07 00:10
Engine has a PR up btw.

**Comment by jessfraz** [comment] 2024-08-13 06:29
looks like this was closed in engine, we good here?

**Comment by Irev-Dev** [comment] 2024-08-29 06:45
Yes.

**Closed** 2024-08-29 06:45 UTC
Labels: bug, high-priority, regression

**Comment by Irev-Dev** [comment] 2024-08-29 06:48
I was about to ping the qa wolf team but looking at this issue on their side it says it's closed already
![image](https://github.com/user-attachments/assets/f8c97218-3f3f-498c-9a8b-7572f3d76218)
