### ISSUE TITLE
Objects visibly pop in

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#2676] opened 2024-06-17 15:53 UTC
A major goal of ours is "speed". It completely kills the selling of that goal.

We need to eliminate any instances of this, at least for < 100 objects as an initial goal, so let's start with that.

**Comment by adamchalmers** [comment] 2024-06-17 19:18
this is just an issue saying "batch everything"

**Comment by adamchalmers** [comment] 2024-06-17 19:19
duplicate of https://github.com/KittyCAD/modeling-app/issues/1972

**Comment by lf94** [comment] 2024-06-17 19:21
Pretty much and why I assigned you too

It may not be a duplicate though, because you may find another strategy. This is **specifically for first model loading**.

**Closed** 2024-07-04 05:55 UTC
Labels: high priority
