### ISSUE TITLE
Commenting out line via // in a fillet tags list causes syntax error - unexpected token 

### ISSUE THREAD

**Issue by yeroca** [KittyCAD/modeling-app#3479] opened 2024-08-16 06:31 UTC
[Add a title above and insert a description of the issue here]

Title line pretty much describes the whole thing.  Code attached here has first tag in fillet commented out, and results in a syntax error, which I think it shouldn't.  // should just cause the rest of the line to be ignored, and lexical parsing should resume on the following line.

Am I using the wrong commenting syntax?

![Screenshot](https://public.blob.zoo.dev/93c47d19-eabe-4565-9357-f1551381005d/modeling-app/coredump-811d9c30-5d92-4421-ba42-893b94cd8721-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-811d9c30-5d92-4421-ba42-893b94cd8721.json](https://public.blob.zoo.dev/0a6e0168-6b78-4b30-8ce5-49f23c38edfa/modeling-app/coredump-811d9c30-5d92-4421-ba42-893b94cd8721.json)

Reference ID: 811d9c30-5d92-4421-ba42-893b94cd8721
</details>

<details>
<summary><b>KCL Code</b></summary>

```kcl
const holeFudge = 0.4
const frontBarD = 5.0
const yBarD = 6.7
const lowerBlockTransHoleD = frontBarD + holeFudge
const lowerBlockTransHoleR = lowerBlockTransHoleD / 2
const upperBlockLongHoleD = yBarD + holeFudge
const upperBlockLongHoleR = upperBlockLongHoleD / 2
const upperBlockTransHoleD = yBarD + holeFudge
const upperBlockTransHoleR = upperBlockTransHoleD / 2
const tubeClr = 1.5
const lowerBlockH = lowerBlockTransHoleD + 2 * tubeClr
const upperBlockH = upperBlockLongHoleD + 2 * tubeClr
const elevateH = 15
const upperBlockL = 25
const lowerBlockL = 35
const blockSz = max(upperBlockH, lowerBlockH)
const sketch001 = startSketchOn('XZ')
  |> startProfileAt([0, 0], %)
  |> yLine(blockSz, %, $edgeA)
  |> xLine(blockSz, %, $edgeB)
  |> yLine(-blockSz, %, $edgeC)
  |> xLine(upperBlockL - blockSz, %, $edge1)
  |> yLine(-(elevateH + blockSz), %, $edge2)
  |> xLine(lowerBlockL - blockSz, %, $edge3)
  |> yLine(-blockSz, %, $edge4)
  |> xLine(-lowerBlockL, %, $edge5)
  |> yLine(blockSz + elevateH, %, $edge6)
  |> xLine(-(upperBlockL - blockSz), %, $edge7)
  |> lineTo([profileStartX(%), profileStartY(%)], %, $seg01)
  |> close(%)
  |> hole(circle([blockSz / 2, blockSz / 2], upperBlockTransHoleR, %), %)
  |> hole(circle([
       upperBlockL + lowerBlockL - blockSz - (lowerBlockTransHoleR) - tubeClr,
       -(blockSz + elevateH + blockSz / 2)
     ], lowerBlockTransHoleR, %), %)
const rad = 3
const extrude001 = extrude(blockSz, sketch001)
  |> fillet({
       radius: rad,
       tags: [
         // getNextAdjacentEdge(edgeA),
         getNextAdjacentEdge(edgeB),
         getNextAdjacentEdge(edgeC),
         getNextAdjacentEdge(edge2),
         getNextAdjacentEdge(edge3),
         getNextAdjacentEdge(edge4),
         getNextAdjacentEdge(edge5),
         getNextAdjacentEdge(edge6)
       ]
     }, %)

const sketch002 = startSketchOn(extrude001, seg01)
   |> startProfileAt([0, 0], %)
   |> circle([blockSz / 2, -blockSz / 2], upperBlockLongHoleR, %)
const extrude2 = extrude(-upperBlockL, sketch002)

```
</details>

**Comment by jtran** [comment] 2024-08-16 13:09
Duplicate?

- #1528

**Comment by yeroca** [comment] 2024-08-17 00:20
> Duplicate?
> 
>     * [KCL: Inline comments for multiline expressions #1528](https://github.com/KittyCAD/modeling-app/issues/1528)

Yes, sorry, please mark as duplicate and close.

**Comment by jessfraz** [comment] 2024-08-19 19:37
closing as dupe of https://github.com/KittyCAD/modeling-app/issues/1528 also removed the low priority from that one as we should fix it

**Closed by jessfraz** 2024-08-19 19:37 UTC
