### ISSUE TITLE
Enable multiple profiles in one sketch

### ISSUE THREAD

**Issue by Irev-Dev** [KittyCAD/modeling-app#1554] opened 2024-02-27 23:07 UTC
Think trying to sketch the outline a doughnut, you need the inner and outer ring, We should enable this in one sketch mode session

code would be
```typescript
const part = startSketchOn('XY')
  |> startProfileAt([...], %) // first
  |> Line(...)
  |> Line(...)
  |> close(%)
  |> startProfileAt([...], %) // second
  |> Line(...)
  |> Line(...)
  |> close(%)
```
This mean that the sketch group data will need to change to allow more nested data (array of arrays perhaps). In this regards it might be worth doing this issue https://github.com/KittyCAD/modeling-app/issues/1553 at the same time.

**Comment by jessfraz** [comment] 2024-05-21 06:26
related to https://github.com/KittyCAD/modeling-app/issues/1876

**Comment by jessfraz** [comment] 2024-05-30 19:01
closing as dupe of https://github.com/KittyCAD/modeling-app/issues/1876

**Closed by jessfraz** 2024-05-30 19:01 UTC
Labels: kcl
