### ISSUE TITLE
Second Sketch on Face dependency doesn't work

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#1511] opened 2024-02-23 20:20 UTC
**Version**
v0.15.2

The first Sketch on Face works no problem. The second doesn't work. I triple-checked my code and I'm pretty certain it should work. The video doesn't help a whole lot, I apologize.

https://github.com/KittyCAD/modeling-app/assets/114548659/1dfafa41-f497-4699-8cec-158cddfb42dc

**KCL**
```
const length = 4
const width = 2
const secondExtrudeWidth = 0.5

fn circle = (pos, radius) => {
  const sg = startSketchOn('XY')
  |> startProfileAt([pos[0] + radius, pos[1]], %)
  |> arc({
       angle_end: 360,
       angle_start: 0,
       radius: radius
     }, %)
  |> close(%)
  return sg
}

const part001 = startSketchOn('XY')
  |> startProfileAt([0, 0], %)
  |> line([length, 0], %)
  |> yLine(width, %)
  |> xLine(-length, %)
  |> close(%)
  |> hole(circle([.5, 1], .25), %)
  |> hole(circle([length - 0.5, 1], .25), %)
  |> extrude(.5, %)

const secondExtrude = startSketchOn(part001, 'end')
  |> startProfileAt([
       length / 2 - (secondExtrudeWidth / 2),
       0
     ], %)
  |> line([0.5, 0], %)
  |> line({ to: [0, 2], tag: "here" }, %)
  |> line([-0.5, 0], %)
  |> close(%)
  |> extrude(3, %)

const secondHole = startSketchOn(secondExtrude, 'here')
  |> startProfileAt([0, 0], %)
  |> line([1, 1], %)
  |> line([0, 2], %)
  |> line([-2, 0], %)
  |> close(%)
  |> extrude(4, %)
```

**Comment by jessfraz** [comment] 2024-02-23 21:17
closing as dupe of https://github.com/KittyCAD/modeling-app/issues/1492 lee beat you :)

**Closed by jessfraz** 2024-02-23 21:17 UTC
