### ISSUE TITLE
Grayed out UI, nothing is clickable

### ISSUE THREAD

**Issue by BlenderChen** [KittyCAD/modeling-app#4231] opened 2024-10-18 23:02 UTC
[Add a title above and insert a description of the issue here]

![Screenshot](https://public.blob.zoo.dev/1f097c71-f9a9-40a7-b57a-b8193b6c4c86/modeling-app/coredump-335fb762-cd1c-4d1e-92bf-35bb977c1d3f-screenshot.png)

<details>
<summary><b>Core Dump</b></summary>

[coredump-335fb762-cd1c-4d1e-92bf-35bb977c1d3f.json](https://public.blob.zoo.dev/63ca5dc2-1d65-467d-8b34-7366d853037b/modeling-app/coredump-335fb762-cd1c-4d1e-92bf-35bb977c1d3f.json)

Reference ID: 335fb762-cd1c-4d1e-92bf-35bb977c1d3f
</details>

<details>
<summary><b>KCL Code</b></summary>

```kcl


sketch002 = startSketchOn('XZ')
  |> startProfileAt([0.262, -0.354], %)
  |> line([0, 0.95], %)

sketch003 = startSketchOn('XZ')
  |> startProfileAt([0.362, -0.354], %)
  |> line([0, 0.354], %)

sketch004 = startSketchOn('XZ')
  |> startProfileAt([0.262, -0.354], %)
  |> line([0.1, 0], %)

sketch005 = startSketchOn('XZ')
  |> startProfileAt([0.362, 0], %)
  |> line([0.13, 0], %)

sketch006 = startSketchOn('XZ')
  |> startProfileAt([0, 1.024], %)
  |> line([0, -0.08], %)
```
</details>

**Comment by pierremtb** [comment] 2024-10-18 23:05
Thanks for sending the coredump @BlenderChen.

@franknoirot this was @BlenderChen and @JordanNoone experiencing a bug where everything in the UI was suddenly grayed out and not clickable. I told them to submit a coredump and that somehow resolved the issue (after the focus change to github.com, submitting the bug, and going back to the app, not sure if that mattered)

**Comment by franknoirot** [comment] 2024-10-22 13:47
Thank you @pierremtb this is a big one. I'm going to retry a blank slate install with no settings and see if I can reproduce it.

**Comment by franknoirot** [comment] 2024-10-22 22:40
This is duplicate of #4215 but I'll close both with my PR

**Closed** 2024-10-23 00:22 UTC
Labels: bug, duplicate

**Comment by pierremtb** [comment] 2024-10-24 22:16
Awesome thanks @franknoirot
