### ISSUE TITLE
Allow modeling tools to disable editing for parts of the AST while equipped

### ISSUE THREAD

**Issue by franknoirot** [KittyCAD/modeling-app#1542] opened 2024-02-27 06:18 UTC
Currently, if a user creates it edits a sketch using the GUI and deletes the `startSketchOn` they are currently working in via the code editor, they can enter an invalid and brittle state.

Instead, deleting this statement should trigger some cleanup if the user is currently in the sketch. @Irev-Dev  this to me seems to suggest something like lifecycle methods that might be good for our lines of code or rather AST nodes to have?

**Comment by Irev-Dev** [comment] 2024-02-27 08:51
> this to me seems to suggest something like lifecycle methods that might be good for our lines of code or rather AST nodes to have?

Sorry could you clarify what you mean? I'm a bit lost. My guess is you saying watching for a source range rather than a path to node changing?

Aside from that I think we should block editing this line until the user has added at least the "startProfileAt" line

Currently we already remove the "startSketchOn" line if the user bails without adding any segments, so this will already get cleaned up and I think that's the legitimate way to exit a sketch

https://github.com/KittyCAD/modeling-app/assets/29681384/07172276-5471-48ed-9c3f-1b84e10a18c0

(ps I noticed a bug that this clean up only works if it's not your first sketch so I need to fix that)

in general editing the code while is sketch mode leads to some nasty behaviour that I'd need to solve more generally I think.
I think we should bring in my litterbox extension to only allow edits of the sketch pipe while in sketch mode.

**Comment by franknoirot** [comment] 2024-02-27 18:27
Totally cool with disabling editing of parts of the code based on the context, I just think it better preserves the design principle of 1:1 bidirectional editing to always allow editing the code directly. In deleting a line of kcl code that generates an engine command to enter a mode (like sketch mode), the user would be generating an engine command to exit that mode if they're in it. Never mind the lifecycle metaphor, I think I see a way of framing your solution in a way that makes sense to me.

I've been feeling like our use of cursor location / selection is a little overloaded right now. It controls both selection and mode (sketch, 3D). I think your idea of making parts of the code uneditable with the litterbox extension is something like a "focus area". _That_ should be what maps to a "mode" in the engine. You must cancel or accept it to unlock editing the other code.

**Comment by franknoirot** [comment] 2024-02-27 19:44
Here are some more thoughts on this. tldw;
- commands ↔ XState self-events ↔ text editor code mods
  - execute once and return to previous state
- tools ↔ XState services ↔ text editor focus areas
  - need to be equipped
  - need to be unequipped, either confirmed or canceled
  - can contain tools and commands within them
  - can disable parts of the AST from being edited while equipped


https://github.com/KittyCAD/modeling-app/assets/23481541/d7968a71-e970-408d-820e-304d7447a82c

**Comment by Irev-Dev** [comment] 2024-02-27 20:07
My one other thought though is you mentioned it being a plug in. I think it's likely this will need to be implemented first not as a plugin and can be refactored later.

I might be wrong, but I get the impression that the plugin architecture will be a substantial project in itself, no?

**Comment by franknoirot** [comment] 2024-02-27 20:58
> Sorry if the un-editable text is a bit of a curve ball when tools are equipped, but I think it's much lower risk move for use. Both in terms of
> a) us not having to be able to be ready for any code change whatsoever and knowing how to react to it.
> b) Users not getting lost when they delete some code and not understanding why it moved them out of sketch or similar

Yeah you're totally right, it simplifies so much on that front. I'm satisfied now that I have a conceptual mapping.

> My one other thought though is you mentioned it being a plug in. I think it's likely this will need to be implemented first not as a plugin and can be refactored later.

Also totally right. Making the code editor use a "core plugin" interface—and even having a plugin architecture at all—is definitely not a priority right now, just something I want to highlight as a long-term goal. I'll link to a discussion on plugin architecture once I start it.

**Comment by jessfraz** [comment] 2024-06-22 21:56
closing as dupe of https://github.com/KittyCAD/modeling-app/issues/1623

**Closed by jessfraz** 2024-06-22 21:56 UTC
Labels: bug, ast, sketch
