### ISSUE TITLE
Stream died no me today while running a test case

### ISSUE THREAD

**Issue by mlfarrell** [KittyCAD/modeling-app#1782] opened 2024-03-20 17:19 UTC
reproducing https://github.com/KittyCAD/engine/issues/1875

all I did was move up and down the code and move the mouse a bit, now stream does not respond to any commands, including mouse.

```
Full URL for WASM: https://app.zoo.dev/wasm_lib_bg.wasm index-rjK1x8im.js:1030:34774
Could not find "window.__TAURI_METADATA__". The "appWindow" value will reference the "main" window label.
Note that this is not an issue if running this frontend on a browser instead of a Tauri window. index-rjK1x8im.js:4801:78759
Object { kind: "syntax", sourceRanges: (1) […], msg: "Cannot assign a variable to a reserved keyword: circle" }
index-rjK1x8im.js:1030:35022
error parsing code 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Cannot assign a variable to a reserved keyword: circle" }
index-rjK1x8im.js:4785:5912
start kcl lsp index-rjK1x8im.js:1030:36092
Uncaught (in promise) Error: auth token is required for copilot
    start https://app.zoo.dev/assets/index-rjK1x8im.js:4851
    <anonymous> https://app.zoo.dev/assets/index-rjK1x8im.js:4958
index-rjK1x8im.js:4851:749
kcl lsp failed Server Error: 401 Unauthorized {
  "request_id": "8ccbc626-882e-4f51-9a51-1994021ff11a",
  "error_code": "Unauthorized",
  "message": "credentials missing or invalid"
} index-rjK1x8im.js:1030:36147
{"type":"fresh"} → {"type":"connecting","value":{"type":"websocket-connecting"}} index-rjK1x8im.js:4716:172333
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
engine connection is not ready index-rjK1x8im.js:4801:35324
{"type":"connecting","value":{"type":"websocket-connecting"}} → {"type":"connecting","value":{"type":"websocket-established"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"websocket-established"}} → {"type":"connecting","value":{"type":"data-channel-requested","value":"unreliable_modeling_cmds"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"data-channel-requested","value":"unreliable_modeling_cmds"}} → {"type":"connecting","value":{"type":"peer-connection-created"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"peer-connection-created"}} → {"type":"connecting","value":{"type":"ice-servers-set"}} index-rjK1x8im.js:4716:172333
Object { type: "offer", sdp: "v=0\r\no=mozilla...THIS_IS_SDPARTA-99.0 4001468376891351594 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 F1:E3:68:57:93:88:15:5F:8B:B7:14:D2:FD:9F:BE:E8:52:F5:A2:07:2F:C8:CB:D1:04:6A:5B:D7:34:CE:2A:2F\r\na=group:BUNDLE 0 1\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=video 9 UDP/TLS/RTP/SAVPF 120 124 121 125 126 127 97 98 123 122 119\r\nc=IN IP4 0.0.0.0\r\na=recvonly\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extmap:5 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=extmap:7 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01\r\na=fmtp:126 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\na=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1\r\na=fmtp:120 max-fs=12288;max-fr=60\r\na=fmtp:124 apt=120\r\na=fmtp:121 max-fs=12288;max-fr=60\r\na=fmtp:125 apt=121\r\na=fmtp:127 apt=126\r\na=fmtp:98 apt=97\r\na=fmtp:119 apt=122\r\na=ice-pwd:3d331c3ea5821be2b1fa456b43abe55a\r\na=ice-ufrag:cef881f2\r\na=mid:0\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=rtcp-fb:120 ccm fir\r\na=rtcp-fb:120 goog-remb\r\na=rtcp-fb:120 transport-cc\r\na=rtcp-fb:121 nack\r\na=rtcp-fb:121 nack pli\r\na=rtcp-fb:121 ccm fir\r\na=rtcp-fb:121 goog-remb\r\na=rtcp-fb:121 transport-cc\r\na=rtcp-fb:126 nack\r\na=rtcp-fb:126 nack pli\r\na=rtcp-fb:126 ccm fir\r\na=rtcp-fb:126 goog-remb\r\na=rtcp-fb:126 transport-cc\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 ccm fir\r\na=rtcp-fb:97 goog-remb\r\na=rtcp-fb:97 transport-cc\r\na=rtcp-fb:123 nack\r\na=rtcp-fb:123 nack pli\r\na=rtcp-fb:123 ccm fir\r\na=rtcp-fb:123 goog-remb\r\na=rtcp-fb:123 transport-cc\r\na=rtcp-fb:122 nack\r\na=rtcp-fb:122 nack pli\r\na=rtcp-fb:122 ccm fir\r\na=rtcp-fb:122 goog-remb\r\na=rtcp-fb:122 transport-cc\r\na=rtcp-mux\r\na=rtcp-rsize\r\na=rtpmap:120 VP8/90000\r\na=rtpmap:124 rtx/90000\r\na=rtpmap:121 VP9/90000\r\na=rtpmap:125 rtx/90000\r\na=rtpmap:126 H264/90000\r\na=rtpmap:127 rtx/90000\r\na=rtpmap:97 H264/90000\r\na=rtpmap:98 rtx/90000\r\na=rtpmap:123 ulpfec/90000\r\na=rtpmap:122 red/90000\r\na=rtpmap:119 rtx/90000\r\na=setup:actpass\r\na=ssrc:2673267158 cname:{ecb72cd8-bdae-405b-b035-3cb7b2a3cc8a}\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=ice-pwd:3d331c3ea5821be2b1fa456b43abe55a\r\na=ice-ufrag:cef881f2\r\na=mid:1\r\na=setup:actpass\r\na=sctp-port:5000\r\na=max-message-size:1073741823\r\n" }
index-rjK1x8im.js:4720:582
{"type":"connecting","value":{"type":"ice-servers-set"}} → {"type":"connecting","value":{"type":"set-local-description"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"set-local-description"}} → {"type":"connecting","value":{"type":"offered-sdp"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"offered-sdp"}} → {"type":"connecting","value":{"type":"received-sdp"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"received-sdp"}} → {"type":"connecting","value":{"type":"set-remote-description"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"set-remote-description"}} → {"type":"connecting","value":{"type":"webrtc-connecting"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"webrtc-connecting"}} → {"type":"connecting","value":{"type":"track-received"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"track-received"}} → {"type":"connecting","value":{"type":"ice-candidate-received"}} index-rjK1x8im.js:4716:172333
connectionstatechange: connecting index-rjK1x8im.js:4716:173537
{"type":"connecting","value":{"type":"ice-candidate-received"}} → {"type":"connecting","value":{"type":"ice-candidate-received"}} 2 index-rjK1x8im.js:4716:172333
trickle_ice: using this candidate:  
Object { candidate: "candidate:40774577 1 udp 2130706431 10.34.7.206 41915 typ host", sdpMid: "", sdpMLineIndex: 0, usernameFragment: null }
index-rjK1x8im.js:4720:1348
connectionstatechange: connected index-rjK1x8im.js:4716:173537
received track 
MediaStream { id: "fcd7e6ea-19d9-4d3b-a2f9-24cdbfd7a664", active: false, onaddtrack: null, onremovetrack: null }
index-rjK1x8im.js:4720:4904
{"type":"connecting","value":{"type":"ice-candidate-received"}} → {"type":"connecting","value":{"type":"data-channel-connecting","value":"unreliable_modeling_cmds"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"data-channel-connecting","value":"unreliable_modeling_cmds"}} → {"type":"connecting","value":{"type":"data-channel-established"}} index-rjK1x8im.js:4716:172333
{"type":"connecting","value":{"type":"data-channel-established"}} → {"type":"connection-established"} index-rjK1x8im.js:4716:172333
sending command make_axes_gizmo index-rjK1x8im.js:4720:9173
sending command default_camera_get_settings index-rjK1x8im.js:4720:9173
sending command make_plane index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command plane_set_color index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command object_visible index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command make_plane index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command plane_set_color index-rjK1x8im.js:4720:9173
sending command object_visible index-rjK1x8im.js:4720:9173
sending command make_plane index-rjK1x8im.js:4720:9173
sending command plane_set_color index-rjK1x8im.js:4720:9173
sending command object_visible index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Cannot assign a variable to a reserved keyword: circle" }
index-rjK1x8im.js:1030:35022
Uncaught (in promise) 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Cannot assign a variable to a reserved keyword: circle" }

sending command highlight_set_entity index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected token" }
index-rjK1x8im.js:1030:35022
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected token" }
index-rjK1x8im.js:4785:3863
console.trace() executeAst index-rjK1x8im.js:4785:6196
    executeAst https://app.zoo.dev/assets/index-rjK1x8im.js:4785
    ife https://app.zoo.dev/assets/index-rjK1x8im.js:4785
    i https://app.zoo.dev/assets/index-rjK1x8im.js:1030
{"kind":"type","sourceRanges":[[412,426]],"msg":"Expected a segment name that exists in the given SketchGroup, found `a`"} index-rjK1x8im.js:1030:35297
Object { kind: "type", sourceRanges: (1) […], msg: "Expected a segment name that exists in the given SketchGroup, found `a`" }
index-rjK1x8im.js:1030:35393
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
not implemented: FunctionExpression index-rjK1x8im.js:1031:23658
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features! new
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected token" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected token" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression 2 index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
not implemented: MemberExpression index-rjK1x8im.js:1031:23658
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected token" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected token" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
error parsing code in processCodeMirrorRanges 
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4801:34663
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:1030:35022
Object { kind: "syntax", sourceRanges: (1) […], msg: "Unexpected end of file. The compiler expected a function body items (functions are made up of variable declarations, expressions, and return statements, each of those is a possible body item" }
index-rjK1x8im.js:4785:3863
console.trace() executeAst index-rjK1x8im.js:4785:6196
    executeAst https://app.zoo.dev/assets/index-rjK1x8im.js:4785
    ife https://app.zoo.dev/assets/index-rjK1x8im.js:4785
    i https://app.zoo.dev/assets/index-rjK1x8im.js:1030
Error in response to request 14bd1b45-77b4-4561-b78c-3f253500abbd:
  - bad_request: No such object exists
failed cmd type was undefined index-rjK1x8im.js:4717:100
undefined index-rjK1x8im.js:4719:63
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_start index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command camera_drag_end index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command default_camera_zoom index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_start index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command camera_drag_end index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command default_camera_zoom index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
WebSocket { url: "wss://api.zoo.dev/ws/modeling/commands?video_res_width=1368&video_res_height=748", readyState: 3, bufferedAmount: 8137, onopen: null, onerror: null, onclose: null, extensions: "", protocol: "", onmessage: null, binaryType: "arraybuffer" }
 
RTCPeerConnection { signalingState: "closed", canTrickleIceCandidates: false, iceGatheringState: "complete", iceConnectionState: "closed", connectionState: "closed", peerIdentity: Promise { "pending" }, idpLoginUrl: null, onnegotiationneeded: null, onicecandidate: null, onsignalingstatechange: null }
 
RTCDataChannel { label: "unreliable_modeling_cmds", negotiated: false, ordered: false, reliable: true, maxPacketLifeTime: null, maxRetransmits: null, protocol: "", id: 2, readyState: "closing", bufferedAmount: 0 }
index-rjK1x8im.js:4720:2358
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_start index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command camera_drag_end index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_start index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command camera_drag_end index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_start index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command camera_drag_end index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command select_clear index-rjK1x8im.js:4720:9173
sending command select_add index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_start index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command camera_drag_end index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_start index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command camera_drag_end index-rjK1x8im.js:4720:9173
sending command select_with_point index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
sending command camera_drag_move index-rjK1x8im.js:4720:9173
sending command highlight_set_entity index-rjK1x8im.js:4720:9173
```

**Comment by Irev-Dev** [comment] 2024-03-21 02:06
Are you able to give us the code you had at the time?

**Comment by jessfraz** [comment] 2024-05-23 01:54
hmm the code doesnt work and errors well for me over here, I had found quite places a few monnths ago in my big editor lsp cleanup where errors were not handled properly see https://github.com/KittyCAD/modeling-app/issues/2022#issuecomment-2126044209 for an explanation of why gregs old bug is fine now as well, I am going to close this as I cannot reproduce and eff-ed around with it for awhile but holding mike up to telling us if he sees it again

**Closed by jessfraz** 2024-05-23 01:54 UTC
Labels: bug, high priority
