### ISSUE TITLE
After tutorial model is zoomed far out

### ISSUE THREAD

**Issue by lf94** [KittyCAD/modeling-app#1920] opened 2024-03-27 15:17 UTC
You can see this here https://youtu.be/NEkh8A-pmSM?t=412

**Comment by jessfraz** [comment] 2024-05-21 06:30
this is dupe of https://github.com/KittyCAD/modeling-app/issues/1874 will be fixed w zoom to fit

**Closed by jessfraz** 2024-05-21 06:30 UTC
