### ISSUE TITLE
Weird Syntax Highlighting on `close` statements

### ISSUE THREAD

**Issue by jgomez720** [KittyCAD/modeling-app#2255] opened 2024-04-25 21:47 UTC
## Description
on `close(%)` statements, the syntax highlighting gets messed up when you try to add a tag. It looks like I have an error in the KCL below.

## Picture
<img width="1912" alt="Screenshot 2024-04-25 at 2 44 31 PM" src="https://github.com/KittyCAD/modeling-app/assets/114548659/31105e2c-ffe0-4696-967e-b15e53500ab0">

## KCL 
```js
const width = 10
const length = 4
const thickness = 0.25
const mountingHoleDia = .5
const holeDia = 1
const clearance = 0.20 + mountingHoleDia/2
const cornerFilletRad = 0.5

const sketch001 = startSketchOn("XY")
  |> startProfileAt([-width/2, -length/2], %)
  |> lineTo([width/2, -length/2], %, 'fillet1')
  |> lineTo([width/2, length/2], %, 'fillet2')
  |> lineTo([-width/2, length/2], %, 'fillet3')
  |> close(%, 'fillet4') // <------ this line
  |> hole(circle([0, 0], holeDia/2, %), %)
  |> hole(circle([-(width/2 - clearance), -(length/2 - clearance)], mountingHoleDia/2, %), %)
  |> hole(circle([-(width/2 - clearance), (length/2 - clearance)], mountingHoleDia/2, %), %)
  |> hole(circle([(width/2 - clearance), (length/2 - clearance)], mountingHoleDia/2, %), %)
  |> hole(circle([(width/2 - clearance), -(length/2 - clearance)], mountingHoleDia/2, %), %)
```

**Comment by jgomez720** [comment] 2024-04-25 21:48
I made a guess that this is related to codemirror lol

**Comment by jessfraz** [comment] 2024-04-25 22:41
dupe of https://github.com/KittyCAD/modeling-app/issues/2214

**Closed by jessfraz** 2024-04-25 22:41 UTC
Labels: codemirror
