### ISSUE TITLE
Default sketch is very large and offsets the planes graph

### ISSUE THREAD

**Issue by ZooSpiritWolf** [KittyCAD/modeling-app#2656] opened 2024-06-14 15:31 UTC
🐛 on Dev

Steps to reproduce:
1. Log into app
2. Observe the default sketch size 
3. Click "Start Sketch"
4. Observe planes offset
Expected: Planes to be centered and default sketch to be at a smaller scale
Actual: Default sketch is very large offsetting the planes 

Timestamp: 0:03
Video: 
https://www.loom.com/share/9fc90a34ca36487c81fe5fa3111548ff?sid=ff052f6a-0bb5-4418-a56a-345a4d976c82 (https://www.loom.com/share/9fc90a34ca36487c81fe5fa3111548ff?sid=ff052f6a-0bb5-4418-a56a-345a4d976c82)

Bug report:
https://app.qawolf.com/zoo/bug-reports/c2a56f28-7ccd-4889-9862-fda2e0110065

Affected workflows:
• Start , Edit, and Delete a sketch - https://app.qawolf.com/zoo/workflows/clw9mdyg10sp8orodfdsok6h5

If you are aware of this bug you can set the priority to low which will prevent it from causing a run failure.

**Comment by lf94** [comment] 2024-06-24 15:27
So it's not that the sketch is very large, it's that zoom-to-fit is doing its job and the resulting grid is at 1mm scale. It's not a bug but more like just a visual eyesore. This'll be fixed when we disable the grid.

**Comment by jessfraz** [comment] 2024-08-04 23:39
reopening since failing in qawolf

**Comment by jessfraz** [comment] 2024-08-05 00:49
this is still a bug since the planes are off center, see qawolf

**Comment by franknoirot** [comment] 2024-08-05 11:07
Ah we should re-center the camera whenever the scene becomes empty again, or maybe fire our "reset camera" action.

**Comment by franknoirot** [comment] 2024-08-05 16:12
My approach for a fix seems to have been a dead end, as it resulted in other strange zoom behavior.

**Comment by lf94** [comment] 2024-08-06 01:19
We can maybe squash this together tomorrow @franknoirot

**Comment by Irev-Dev** [comment] 2024-08-06 05:20
Sooooo close @franknoirot!

I basically stole your code and tweaked one thing
https://github.com/KittyCAD/modeling-app/pull/3293

long story short is the zoom to fit is kinda weird atm, there's a PR for it up atm that I'm hopeful for, but calling it on an empty scene is asking for trouble, so I just manually put the camera back to it's start position.

I'm not 100% sure if #3293 closes this or not, I'm going to review qa wolfs loom now.

**Comment by Irev-Dev** [comment] 2024-08-06 05:22
Yeah I think it will close it, updating the PR description now.

**Closed** 2024-08-06 07:05 UTC
Labels: bug, high priority

**Comment by franknoirot** [comment] 2024-08-06 12:27
Oh hell yeah thanks so much @Irev-Dev!
